apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-service
  namespace: minecraft-cluster
  labels:
    app: game-service
spec:
  replicas: 2 # You can adjust the number of game service instances
  selector:
    matchLabels:
      app: game-service
  template:
    metadata:
      labels:
        app: game-service
    spec:
      containers:
      - name: game
        image: wi1helm/game:latest # Use the exact image and tag
        ports:
        - containerPort: 8082
        env:
        - name: REDIS_ADDRS
          value: "redis-cluster-0.redis-cluster.minecraft-cluster.svc.cluster.local:6379,redis-cluster-1.redis-cluster.minecraft-cluster.svc.cluster.local:6379,redis-cluster-2.redis-cluster.minecraft-cluster.svc.cluster.local:6379,redis-cluster-3.redis-cluster.minecraft-cluster.svc.cluster.local:6379,redis-cluster-4.redis-cluster.minecraft-cluster.svc.cluster.local:6379,redis-cluster-5.redis-cluster.minecraft-cluster.svc.cluster.local:6379"
        - name: GAME_SERVICE_LISTEN_ADDR
          value: ":8082"
        - name: PLAYERS_SERVICE_URL
          value: "http://player-service:8081" # Internal K8s DNS
        - name: REDIS_ONLINE_TTL
          value: "15s"
        - name: GAME_SERVICE_TICK_INTERVAL
          value: "50ms"
        - name: GAME_SERVICE_PERSISTENCE_INTERVAL
          value: "30s"
        - name: GAME_SERVICE_INSTANCE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['kubernetes.io/replication-controller-instance-id'] # Example for unique ID if needed for sharding, often managed by operator or custom logic. For now, it will be 0.
        - name: TOTAL_GAME_SERVICE_INSTANCES
          value: "2" # Match your replica count for potential sharding
        - name: GAME_BACKUP_TIMEOUT
          value: "60s"
        - name: GAME_SYNC_TIMEOUT
          value: "30s"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SERVICE_HEARTBEAT_INTERVAL
          value: "5s"
        - name: SERVICE_HEARTBEAT_TTL
          value: "15s"
        - name: SERVICE_REGISTRY_CLEANUP_INTERVAL
          value: "30s"
---
apiVersion: v1
kind: Service
metadata:
  name: game-service
  namespace: minecraft-cluster
spec:
  selector:
    app: game-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082